name: 'Restore Firebase Config'
description: 'Restores google-services.json and GoogleService-Info.plist from secrets'

inputs:
  google_services_json:
    description: 'The GOOGLE_SERVICES_JSON secret'
    required: false
  google_service_info_plist:
    description: 'The GOOGLE_SERVICE_INFO_PLIST secret'
    required: false

runs:
  using: "composite"
  steps:
    - name: Restore google-services.json
      if: inputs.google_services_json != ''
      shell: bash
      run: |
        mkdir -p androidApp/src/debug
        if [ -z "${{ inputs.google_services_json }}" ]; then
          echo "Error: google_services_json input is empty."
          exit 1
        fi
        echo "${{ inputs.google_services_json }}" | base64 --decode > androidApp/src/debug/google-services.json
        echo "google-services.json successfully restored."

    - name: Restore GoogleService-Info.plist
      if: inputs.google_service_info_plist != ''
      shell: bash
      run: |
        mkdir -p iosApp/iosApp/FirebaseConfig
        if [ -z "${{ inputs.google_service_info_plist }}" ]; then
          echo "Error: google_service_info_plist input is empty."
          exit 1
        fi
        echo "${{ inputs.google_service_info_plist }}" | base64 --decode > iosApp/iosApp/FirebaseConfig/Debug-GoogleService-Info.plist
        echo "GoogleService-Info.plist restored successfully."