# Helper to get filtered notes
def fetch_notes
    # Gets last commit, removes merges
    sh("git log -1 --pretty=format:'- %s' | grep -v 'Merge pull request' | grep -v 'Merge branch'").strip
end

platform :android do
    desc "Build Debug APK and upload to Firebase"
    lane :distribute_debug do
        # 1. Generate release notes
        notes = fetch_notes

        # 2. Build APK
        gradle(task: ":androidApp:assembleDebug")

        # 3. Upload to Firebase
        firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID_ANDROID"],
            groups: "Internal",
            apk_path: "androidApp/build/outputs/apk/debug/androidApp-debug.apk",
            release_notes: notes,
            service_credentials_file: "firebase-credentials.json",
        )
    end
end


platform :ios do
    desc "Build Debug IPA and upload to Firebase"
    lane :distribute_debug do
        # 1. Generate release notes
        notes = fetch_notes

        # 2. Config api key
        api_key = app_store_connect_api_key(
            key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
            issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
            key_filepath: ENV["APP_STORE_CONNECT_KEY_FILE_PATH"],
            duration: 1200,
            in_house: false
        )

        # 3. Pass the key to Match
        match(type: "adhoc", api_key: api_key)

        # 4. Build IPA
        build_app(scheme: "iosApp", export_method: "ad-hoc")

        # 5. Upload to Firebase
        firebase_app_distribution(
            app: ENV["FIREBASE_APP_ID_IOS"],
            groups: "Internal",
            ipa_path: "build/ios/iosApp.ipa",
            release_notes: notes,
            service_credentials_file: "firebase-credentials.json"
        )
    end
end